version: '3.8'

services:

  db:
    container_name: amazon_product_api_postgres_db
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    # environment:
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: amazon_product_api_redis_cache
    image: redis:latest

  web:
    container_name: amazon_product_api
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./src/config/.env  # مسیر صحیح فایل .env را تنظیم کنید
    # environment:
    #   - SECRET_KEY=${SECRET_KEY}
    #   - DEBUG=${DEBUG}
    #   - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - DATABASE_URL=${DATABASE_URL}
    #   - REDIS_URL=${REDIS_URL}

volumes:
  postgres_data:
